category_dct = {
    'hotel type': {'family' : ['family'], 'accessible' : ['accessible'], 'budget' : ['cheap', 'affordable', 'budget', 'value', 'bargain',  'under 100', 'under 50'], 'boutique' : [ 'boutique'], 'pet-friendly' : ['dogs', 'pet'], 'luxury' : ['luxury', 'exclusive'], 'spa' : ['spa', 'welness'], 'swimming pool' : ['pool'], 'star' : ['star'], 'all inclusive' : ['inclusive'], 'motel' : ['motel'], 'treehouse' : ['treehouse'], 'boat' : ['boat'], 'cabin' : ['cabin'], 'resort' : ['resort'], 'adult only' : ['adult'], 'central' : ['central', 'centre'], 'villa' : ['villa'], 'apartment' : ['apart', 'aparthotel'], 'bed and breakfast' : ['bed and breakfast', 'b and b'], 'guest-house' : ['guest house'], 'romantic' : ['romance', 'romantic', 'charming'], 'eco' : ['eco', 'enviroment', 'eco tourism', 'sustainable'], 'airport' : ['airport'], 'honeymoon' : ['honeymoon', 'mini moon'], 'country' : ['country'], 'beach' : ['beach']},

    'user': {'family' : ['family', 'kid', 'toddler', 'baby', 'babies', 'teen', 'teenager', 'child', 'children'], 'couples' : ['couple', 'boyfriend', 'girlfriend', 'wife', 'husband', 'fiancee', 'partner'], 'solo' : ['solo', 'single', 'individual'], 'pets' : ['dog', 'pet', 'cat'], 'disabled' : ['disabled', 'handicap', 'accessible'], 'LGBTQI' : ['gay', 'lesbian', 'lgbt', 'lgbtqia', 'lgbtqi'], 'senior' : ['senior', 'pensioner', 'elderly'], 'adult' : ['adult'], 'young' : ['young', '18-30'], 'age' : ['years old'], 'group' : ['group', 'small group', 'guests'], 'veteran' : ['veteran']},

    'commercial' : {'deals' : ['promotion', 'promo', 'deals', 'offers', 'discount'], 'flight' : ['flight', 'fly'], 'car hire' : ['car'], 'package' : ['dinner included', 'with breakfast', 'flights', 'package', 'breakfast included'], 'holiday' : ['holiday', 'trip', 'vacation'], 'price' : ['cost', 'price', 'expensive'], 'pay_later' : ['pay later'],'breaks' : ['breaks', 'getaway', 'weekend away']},

    'modifier' : {'best' : ['best', 'top', 'finest', 'leading', 'great', 'favourite', 'beautiful', 'nicest', 'pretty', 'prettiest', 'nice', 'popular', 'good'], 'luxury' : ['luxury', 'exclusive'], 'cheap' : ['cheap', 'affordable', 'budget', 'value', 'bargain',  'under 100', 'under 50'], 'last minute' : ['last minute', 'last-minute', 'last minute deals'], 'peace and quiet' : ['quiet', 'secluded', 'private', 'relaxing', 'peace', 'hidden', 'unknown', 'secret'], 'lively' : ['lively', 'entertainment'], 'quirky' : ['quirky', 'unusual', 'cool', 'interesting', 'unique', 'trendy', 'coolest', 'trendiest'], 'small' : ['small'], 'seafront' : ['seafront', 'waterfront'], 'riverfront' : ['riverfront', 'river view']},

    'services/room features' : {'breakfast' : ['breakfast'], 'shuttle' : ['shuttle'], 'jacuzzi' : ['hot tub', 'jacuzzi'], 'casino' : ['casino'], 'gym' : ['gym', 'fitness'], 'wifi' : ['wifi'], 'room service' : ['room service'], 'tv' : ['tv'], 'afternoon tea' : ['tea'], 'balcony' : ['balcony', 'terrace'], 'view' : ['view'], 'wedding' : ['wedding'], 'laundry' : ['washer', 'dryer', 'ironing', 'laundry', 'washing machine'], 'water_park' : ['water park', 'lazy river'], 'suite' : ['suite'], 'penthouse' : ['penthouse'], 'parking' : ['free parking', 'parking'], 'smoking' : ['smoking'], 'non_smoking' : ['non-smoking', 'non smoking', 'no smoking', 'smoke free'], 'childcare' : ['childcare', 'childrens entertainment', 'babysitting', 'baby sitting', 'nanny'], 'air_conditioning' : ['air conditioning', 'ac', 'airconditioning']},

    'time of year' : {'january' : ['january'], 'february' : ['february'], 'march' : ['march'], 'may' : ['may'], 'june' : ['june'], 'july' : ['july'], 'august' : ['august'], 'september' : ['september'], 'november' : ['november'], 'december' : ['december'], 'winter' : ['winter'], 'summer' : ['summer'], 'spring' : ['spring'], 'autumn' : ['autumn']},

    'FAQs' : {'how' : ['how'], 'what' : ['what'], 'where' : ['where'], 'when' : ['when'], 'why' : ['why'], 'can' : ['can'], 'things to do' : ['things to do'], 'will' : ['will'], 'which' : ['which'], 'have' : ['have'], 'should' : ['should'], 'was' : ['was'], 'do' : ['do'], 'is' : ['is'], 'could' : ['could'], 'would' : ['would']},

    'location' : {'Pleasure Beach' : ['pleasure beach'], 'North Shore' : ['north', 'north shore'], 'Winter Gardens' : ['winter gardens'], 'Albert Road' : ['albert road'], 'Central' : ['central', 'centre'], 'Blackpool Tower' : ['tower'], 'Lord Street' : ['lord street'], 'South Shore' : ['south'], 'Promenade' : ['promenade'], 'St Annes' : ['st annes'], 'Cleveleys' : ['cleveleys'], 'Coral Island' : ['coral island'], 'Illuminations' : ['illuminations'], 'Hornby Road' : ['hornby road'], 'Blackpool FC ' : ['blackpool football club '], 'Grand Theatre' : ['theatre'], 'Stanley Park' : ['stanley park'], 'Ballroom' : ['ballroom'], 'Charnley Road' : ['charnley road'], 'Adelaide Street' : ['adelaide street'], 'St Chads Road' : ['st chads road'], 'near / close to' : ['close', 'near']},

    'brands' : {'american airlines' : ['american airlines'], 'ryanir' : ['ryanir'], 'british airways' : ['ba', 'british airways'], 'easyjet' : ['easyjet'], 'thomas cook' : ['thomas cook'], 'tui' : ['tui'], 'atol' : ['atol'], 'abta' : ['abta'], 'social media' : ['facebook', 'instagram', 'twitter', 'tik tok', 'whatsapp'], 'jet2' : ['jet2'], 'first choice' : ['first choice'], 'enterprise' : ['enterprise'], 'avis' : ['avis'], 'alamo' : ['alamo'], 'hertz' : ['hertz'], 'martin lewis' : ['martin lewis'], 'tripadvisor' : ['tripadvisor'], 'expedia' : ['expedia'], 'google' : ['google'], 'travelzoo' : ['travel zoo', 'travelzoo'], 'groupon' : ['groupon', 'group on'], 'amazon' : ['amazon'], 'booking.com' : ['booking com', 'booking.com']},
    }
