category_dct = {
    'pdp_queries_info' : {'room' : ['room', 'bedroom', 'bed'], 'reviews' : ['review'], 'parking' : ['parking'], 'photos' : ['photo'],  'check-in/out' : ['checkin', 'check-in', 'check in', 'check-out', 'check out', 'checkout'], 'nearby' : ['near', 'closest'], 'attractions' : ['places to eat', 'takeaways', 'cinemas', 'museum', 'stadium', 'supermarket', 'covention', 'attractions', 'theme park'], 'covid-19' : ['covid', 'coronarvirus'], 'breakfast' : ['breakfast'], 'airport-shuttle' : ['shuttle', 'taxi'], 'ferry' : ['ferries', 'ferry', 'boat']},

    'pdp_commercial' : {'deals' : ['promotion', 'promo', 'deals', 'offers', 'discount'], 'price' : ['price', 'cost', 'fee', 'rates', 'under'], 'booking' : ['book'], 'stay' : ['stay'], 'all-inclusive' : ['inclusive'], 'weddings' : ['wedding'], 'afternoon-tea' : ['tea'], 'pay-later' : ['pay'], 'time to stay' : ['time to stay', 'time to go', 'when to stay'], 'package' : ['dinner included', 'with breakfast', 'flights', 'package', 'breakfast included'], 'escapes' : ['escape', 'getaway', 'short stay'], 'bed and breakfast' : ['bed and breakfast', 'b and b'], 'guest-house' : ['guest house'], 'holiday' : ['holiday', 'trip', 'vacation'], 'staycation' : ['staycation'],'breaks' : ['breaks', 'getaway', 'weekend away'], 'flight' : ['flight', 'airline', 'air fare', 'flying', 'plane', 'airfare'], 'car hire' : ['car rental', 'car hire'], 'balcony' : ['balcony', 'terrace'], 'air_conditioning' : ['air conditioning', 'ac', 'airconditioning'], 'view' : ['view'], 'breakfast' : ['breakfast', 'breakfast included', 'free breakfast'], 'casino' : ['casino'], 'laundry' : ['washer', 'dryer', 'ironing', 'laundry', 'washing machine'], 'water_park' : ['water park', 'lazy river'], 'suite' : ['suite'], 'penthouse' : ['penthouse'], 'parking' : ['free parking', 'parking'], 'smoking' : ['smoking'], 'non_smoking' : ['non-smoking', 'non smoking', 'no smoking', 'smoke free'], 'café' : ['cafe', 'coffee'], 'childcare' : ['childcare', 'childrens entertainment', 'babysitting', 'baby sitting', 'nanny'], 'concierge' : ['concierge'], 'check-in' : ['late check out', 'check out', 'boarding', 'check in'], 'connecting_rooms' : ['connecting room', 'adjoining room'], 'fine_dining' : ['fine dining'], 'excursions' : ['excursion'], 'fireplace' : ['fireplace', 'open fire'], 'poolside_bar' : ['poolside bar', 'swim up bar'], 'seafood' : ['seafood'], 'sports' : ['sports'], 'central' : ['central', 'centre', 'center'], 'honeymoon' : ['honeymoon', 'mini moon'], 'romantic' : ['romance', 'romantic', 'charming'], 'boutique' : ['small', 'boutique'], 'eco' : ['eco', 'enviroment', 'eco tourism', 'sustainable'], 'resort' : ['resorts'], 'historic' : ['historic', 'history'], 'castle' : ['castle'], 'villa' : ['villa'], '7_star' : ['7 star', 'seven star'], '6_star' : ['6 star', 'six star'], '5_star' : ['5 star', 'five star'], '4_star' : ['4 star', 'five star'], '3_star' : ['3 star', 'five star'], '2_star' : ['2 star', 'five star'], '1_star' : ['1 star', 'five star'], 'all_inclusive' : ['all inclusive', 'full board'], 'half_board' : ['half board'], 'airport' : ['near to airport', 'airport'], 'motel' : ['motel'], 'adventure' : ['adventure', 'activity', 'experience'], 'camping' : ['camping', 'outdoors'], 'country_house' : ['country house'], 'travel' : ['travel', 'places to travel'], 'money' : ['credit card', 'debit card', 'money'], 'insurance' : ['insurance'], 'train' : ['train', 'rail'], 'cancellations and delays' : ['delays', 'cancellation', 'compensation']},

    'modifier' : {'best' : ['best', 'top', 'finest', 'leading', 'great', 'favourite', 'beautiful', 'nicest', 'pretty', 'prettiest', 'nice', 'popular'], 'luxury' : ['luxury', 'luxurious', 'expensive', 'exclusive'], 'cheap' : ['cheap', 'affordable', 'budget', 'value', 'bargain',  'under 100', 'under 50', 'low'], 'last minute' : ['last minute', 'last-minute', 'last min', 'last minute deals'], 'pay_later' : ['pay later'], 'peace and quiet' : ['quiet', 'secluded', 'private', 'relaxing', 'peace', 'hidden', 'unknown', 'secret'], 'lively' : ['lively', 'entertainment'], 'quirky' : ['quirky', 'unusual', 'cool', 'interesting', 'unique', 'trendy', 'coolest', 'trendiest'], 'fun' : ['fun']},


    'user': {'family' : ['family', 'kid', 'toddler', 'baby', 'babies', 'teen', 'teenager', 'child', 'children'], 'couples' : ['couple', 'boyfriend', 'girlfriend', 'wife', 'husband', 'fiancee', 'partner'], 'solo' : ['solo', 'single', 'individual'], 'pets' : ['dog', 'pet', 'cat'], 'disabled' : ['disabled', 'handicap', 'accessible'], 'LGBTQI' : ['gay', 'lesbian', 'lgbt', 'lgbtqia', 'lgbtqi'], 'senior' : ['senior', 'pensioner', 'elderly'], 'adult' : ['adult'], 'young' : ['young', '18-30'], 'age' : ['years old'], 'group' : ['group', 'small group', 'guests'], 'veteran' : ['veteran']},

    'pdp_contact' : {'address' : ['address'], 'email' : ['email', 'mail'], 'phone' : ['telephone', 'phone'], 'contact' : ['contact'], 'job' : ['job', 'career']},

    'pdp_amenities' : {'spa' : ['spa', 'welness'], 'swimming pool' : ['pool'], 'restaurant' : ['restaurant', 'dinner', 'menu', 'lunch'], 'casino' : ['casino'], 'gym' : ['gym', 'fitness'], 'wifi' : ['wifi'], 'room service' : ['room service'], 'tv' : ['tv']},

    'time' : {'tonight' : ['tonight'], 'night' : ['night'], 'week_weekend' : ['midweek', 'weekly', 'weekend'], 'seasonal' : ['january', 'february', 'march', 'june', 'july', 'august', 'september', 'november', 'december', 'winter', 'summer', 'spring', 'autumn'], 'last-minute' : ['last minute'], 'events' : ['anniversary', 'birthday', 'halloween', 'easter', 'christmas', 'fathers day', 'new years', 'mothers day', 'oktoberfest', 'world cup', 'tennis']},

    'informational' : {'how' : ['how'], 'what' : ['what'], 'where' : ['where'], 'when' : ['when'], 'why' : ['why'], 'can' : ['can'], 'things to do' : ['things to do'], 'will' : ['will'], 'which' : ['which'], 'have' : ['have'], 'should' : ['should'], 'was' : ['was'], 'do' : ['do'], 'is' : ['is'], 'could' : ['could'], 'would' : ['would'], 'advice' : ['advice'], 'tips' : ['tips'], 'history' : ['history'], 'weather' : ['weather'], 'good' : ['good', 'nice']},

    'brands' : {'american airlines' : ['american airlines'], 'ryanir' : ['ryanir'], 'british airways' : ['ba', 'british airways'], 'easyjet' : ['easyjet'], 'thomas cook' : ['thomas cook'], 'tui' : ['tui'], 'atol' : ['atol'], 'abta' : ['abta'], 'social media' : ['facebook', 'instagram', 'twitter', 'tik tok', 'whatsapp'], 'jet2' : ['jet2'], 'first choice' : ['first choice'], 'enterprise' : ['enterprise'], 'avis' : ['avis'], 'alamo' : ['alamo'], 'hertz' : ['hertz'], 'martin lewis' : ['martin lewis'], 'tripadvisor' : ['tripadvisor'], 'expedia' : ['expedia'], 'google' : ['google'], 'travelzoo' : ['travel zoo', 'travelzoo'], 'groupon' : ['groupon', 'group on'], 'amazon' : ['amazon'], 'booking.com' : ['booking com', 'booking.com'], 'cheap' : ['cheap', 'budget', 'bargain', 'inexpensive']},
    
    }